name: context_watch
description: A hassle-free way to watch for observable value changes within the `build` method.
version: 2.0.0-dev.5
homepage: https://github.com/s0nerik/context_watch
repository: https://github.com/s0nerik/context_watch

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.17.0-1.0.pre.38"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  meta: ^1.9.1
  context_watch_base: ^2.0.0-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
